### ISSUE TITLE
TypeError: src data type = 17 when run train_unet.py

### ISSUE THREAD

**Issue by nhmnmh1997** [notha99y/UNet#3]
raceback (most recent call last):
  File "C:/Users/path/U_Net/src/train_unet.py", line 127, in <module>
    image_path, mask_path, verbose=False, plot=False)
  File "C:\Users\path\U_Net\src\utils.py", line 65, in resizing
    images.append(cv2.resize(img_temp, (320, 240)))
TypeError: src data type = 17 is not supported

**Comment by notha99y** [comment]
Hi @nhmnmh1997 can you provide more details? did you run src/processing.py?

**Comment by nhmnmh1997** [comment]
> Hi @nhmnmh1997 can you provide more details? did you run src/processing.py?

I ran it.
at this: images.append(cv2.resize(img_temp, (320, 240)))
i think cv2.resize not support img_temp = plt.imread...

**Comment by Edwardsleo** [comment]
I ran src/processing.py... i am getting issue while training

Traceback (most recent call last):
  File "src/train_unet.py", line 142, in <module>
    epochs=config["epochs"])
  File "src/train_unet.py", line 100, in train
    verbose=1, callbacks=[checkpoint, tensor_board], validation_split=0.2)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1435, in fit
    batch_size=batch_size)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1315, in _standardize_user_data
    exception_prefix='target')
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 127, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected conv2d_18 to have 4 dimensions, but got array with shape (54912000, 8)

**Comment by notha99y** [comment]
@Edwardsleo what are you inputs? could you print the batch shape?

did you also run `python src/processing.py` before starting the training?

**Comment by Edwardsleo** [comment]
> @Edwardsleo what are you inputs? could you print the batch shape?
> 
> did you also run `python src/processing.py` before starting the training?

Yes i ran python **src/processing.py** as you said in ReadMe.
**On Running training i am getting issue**


2021-07-07 07:00:19.510263: I tensorflow/core/common_runtime/placer.cc:1059] Const_14: (Const)/job:localhost/replica:0/task:0/device:CPU:0

**Getting data.. Image shape: (715, 240, 320, 3). Masks shape : (54912000, 8)
The data will be split to Train Val: 80/20**

Traceback (most recent call last):
  File "src/train_unet.py", line 139, in <module>
    epochs=config["epochs"])
  File "src/train_unet.py", line 100, in train
    verbose=1, callbacks=[checkpoint, tensor_board], validation_split=0.2)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1435, in fit
    batch_size=batch_size)
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 1315, in _standardize_user_data
    exception_prefix='target')
  File "/usr/local/lib/python3.6/dist-packages/keras/engine/training.py", line 127, in _standardize_input_data
    str(array.shape))
ValueError: Error when checking target: expected conv2d_18 to have 4 dimensions, but got array with shape (54912000, 8)

------------------- I tried changing plt.read to cv2.read but no luck
Did we have to tune on Masks shape : (54912000, 8)

**Comment by Edwardsleo** [comment]
--------------------------------------------------------------------------------------------------------------------------
unet json: /mnt/unet/UNet/config/unet.json
Initializing UNet model
Encoding Phase
Stage : 1
========================================
(?, 240, 320, 3)
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/tensorflow/python/framework/op_def_library.py:263: colocate_with (from tensorflow.python.framework.ops) is deprecated and will be removed in a future version.
Instructions for updating:
Colocations handled automatically by placer.
(?, 120, 160, 64)
Stage : 2
========================================
(?, 120, 160, 64)
(?, 60, 80, 128)
Stage : 3
========================================
(?, 60, 80, 128)
(?, 30, 40, 256)
middle phase
========================================
WARNING:tensorflow:From /usr/local/lib/python3.6/dist-packages/keras/backend/tensorflow_backend.py:2880: calling dropout (from tensorflow.python.ops.nn_ops) with keep_prob is deprecated and will be removed in a future version.
Instructions for updating:
Please use `rate` instead of `keep_prob`. Rate should be set to `rate = 1 - keep_prob`.
(?, 30, 40, 512)
Decoding Phase
1
========================================
(?, 30, 40, 512)
src/train_unet.py:62: UserWarning: The `merge` function is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  concat = merge([conv_layers[i-1], up], mode='concat', concat_axis=3)
/usr/local/lib/python3.6/dist-packages/keras/legacy/layers.py:460: UserWarning: The `Merge` layer is deprecated and will be removed after 08/2017. Use instead layers from `keras.layers.merge`, e.g. `add`, `concatenate`, etc.
  name=name)
(?, 60, 80, 256)
2
========================================
(?, 60, 80, 256)
(?, 120, 160, 128)
3
========================================
(?, 120, 160, 128)
(?, 240, 320, 64)

**Comment by Edwardsleo** [comment]
@notha99y 
![Capture](https://user-images.githubusercontent.com/14907243/124715478-ac718380-df20-11eb-9616-32dff8b5cb82.PNG)

**Comment by notha99y** [comment]
@Edwardsleo i think it is because of the tensorflow version.. this code was implemented using tensorflow 1. can i refer you to use https://github.com/google-research/deeplab2 instead?

**Comment by notha99y** [comment]
If you still want to use this repo, I probably have to look into fixing the problem you are facing. Let me know.
